<a href="https://colab.research.google.com/github/joiepark/assignment_esaa/blob/main/8%EC%9B%94%20%EC%8A%A4%ED%84%B0%EB%94%94%3A%20YB%20%EC%BB%A4%EB%A6%AC%ED%81%98%EB%9F%BC%20%EB%B3%B5%EC%8A%B5%201%ED%9A%8C%EC%B0%A8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 1주차


*   ndarray 내 데이터값의 타입 변경은 astype() 메서드를 이용해 할 수 있으며, astype()에 인자로 원하는 타입을 문자열로 지정하면 된다.

In [2]:
import numpy as np

In [3]:
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32



*   특정 크기와 차원을 가진 ndarray를 연속값이나 0 또는 1로 초기화해 쉽게 생성해야 할 필요가 있는 경우에는 arange()를 활용한다. arange()는 파이썬 표준 함수인 range()와 유사한 기능, 즉 array를 range()로 표현하는 기능을 한다. 0부터 함수 인자 값 -1까지의 값을 순차적으로 ndarray의 데이터값으로 변환해준다. default 함수 인자는 stop 값이며, 0부터 stop 값인 10에서 -1을 더한 9까지의 연속 숫자 값으로 구성된 1차원 ndarray를 만들어준다. 여기서는 stop값만 부여했으나 range와 유사하게 start 값도 부여해 0이 아닌 다른 값부터 시작한 연속 값을 부여할 수도 있다.
*  zeros()는 함수 인자로 튜플 형태의 shape 값을 입력하면 모든 값을 0으로 채운 해당 shape을 가진 ndarray를 반환한다.
*  ones()도 유사하게 함수 인자로 튜플 형태의 shape 값을 입력하면 모든 값을 1로 채운 해당 shape를 가진 ndarray를 반환한다. 함수 인자로 dtype을 정해주지 않으면 default로 float64형의 데이터로 ndarray를 채운다.

In [4]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)

In [5]:
zero_array = np.zeros((3, 2), dtype = 'int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3, 2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


*   reshape() 메서드는 ndarray를 특정 차원 및 크기로 변환한다. 변환을 원하는 크기를 함수 인자로 부여하면 된다. 지정된 사이즈로 변경이 불가능하면 오류를 발생시킨다. (e.g. (10,) 데이터를 (4,3) Shape 형태로 변경할 수는 없는 것이다.)
*  reshape()를 실전에서 더욱 효율적으로 사용하는 경우는 아마도 인자로 -1을 적용하는 경우일 것이다. -1을 인자로 사용하면 원래 ndarray와 호환되는 새로운 shape로 변환해준다. (* 물론 -1을 사용하더라도 호환될 수 없는 형태는 변환할 수 없다.)
*  -1 인자는 reshape(-1,1)와 같은 형태로 자주 사용된다. reshape(-1,1)은 원본 ndarray가 어떤 형태라도 2차원이고, 여러 개의 로우를 가지되 반드시 1개의 컬럼을 가진 ndarray로 변환됨을 보장하기 때문이다.

In [6]:
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2, 5)
print('array2:\n', array2)

array3 = array1.reshape(5, 2)
print('array3:\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

In [7]:
array1 = np.arange(10)
print(array1)
array2 = array1.reshape(-1, 5)
print('array2 shape:', array2.shape)
array3 = array1.reshape(5, -1)
print('array3 shape:', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)

In [8]:
array1 = np.arange(8)
array3d = array1.reshape((2, 2, 2))
print('array3d:\n', array3d.tolist())   ## ndarray는 tolist() 메서드를 이용해 리스트 자료형으로 변환할 수 있다

# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1, 1)
print('array5:\n', array5.tolist())
print('array5 shape:', array5.shape)

# 1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1, 1)
print('array6: \n', array6.tolist())
print('array6 shape:', array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)



*   Numpy의 행렬 정렬은 np.sort()와 같이 넘파이에서 sort()를 호출하는 방식이 있고, ndarray.sort()와 같이 행렬 자체에서 sort()를 호출하는 방식이 있다. 전자의 경우 "원 행렬은 그대로 유지한 채로 원 행렬의 정렬된 행렬을 반환"하며, 후자의 경우에는 "원 행렬 자체를 정렬한 형태로 변환"하며 반환 값은 None이다. np.sort()나 ndarray.sort() 모두 기본적으로 오름차순으로 행렬 내 원소를 정렬한다. 내림차순으로 정렬하기 위해서는 [::-1]을 적용한다. (e.g. np.sort()[::-1]과 같이 사용할 수 있다.) 또 행렬이 2차원 이상일 경우, axis 축 값 설정을 통해 로우 방향 또는 칼럼 방향으로 정렬을 수행할 수 있다.
*   원본 행렬이 정렬되었을 떄 기존 원본 행렬의 원소에 대한 인덱스를 필요로 할 수 있다. 이 때 np.argsort()는 정렬 행렬의 원본 행렬 인덱스를 ndarray형으로 반환한다. 오름차순이 아닌 내림차순으로 정렬 시에 원본 행렬의 인덱스를 구하는 것도 np.argsort()[::-1]을 적용하면 된다.
*  argsort()는 넘파이에서 활용도가 매우 높다. 넘파이의 ndarray는 RDBMS의 TABLE 칼럼이나 판다스 DataFrame 칼럼과 같은 메타 데이터를 가질 수 없어, 실제 값과 그 값이 뜻하는 메타 데이터를 별도의 ndarray로 각각 가져야만 한다. 예를 들어, 학생별로 시험 성적을 데이터로 표현하기 위해서는 학생의 이름과 시험 성적을 각각 ndarray로 가져야 한다. 즉 John=78, Mike=95, Sarah=84, Kate=98, Samuel=88을 ndarray로 활용하고자 한다면 name_array=['John', 'Mike', 'Sarah', 'Kate', 'Samuel']와 score_array=[78, 95, 84, 98, 88]과 같이 2개의 ndarray를 만들어야 한다. 이때 시험 성적순으로 학생 이름을 출력하고자 한다면 np.argsort(score_array)를 이용해 반환된 인덱스를 name_array에 팬시 인덱스로 적용해 추출할 수 있다.

In [9]:
org_array = np.array([3, 1, 9, 5])
print('원본 행렬: ', org_array)

# np.sort()로 정렬
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬: ', sort_array1)
print('np.sort() 호출 후 원본 행렬: ', org_array)

# ndarray.sort()로 정렬
sort_array2 = org_array.sort()
print('org_array.sort() 호출 후 반환된 행렬: ', sort_array2)
print('org_array.sort() 호출 후 원본 행렬: ', org_array)

원본 행렬:  [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬:  [1 3 5 9]
np.sort() 호출 후 원본 행렬:  [3 1 9 5]
org_array.sort() 호출 후 반환된 행렬:  None
org_array.sort() 호출 후 원본 행렬:  [1 3 5 9]

In [10]:
sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순으로 정렬: ', sort_array1_desc)

내림차순으로 정렬:  [9 5 3 1]

In [11]:
array2d = np.array([[8, 12],
                    [7, 1]])

sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬: \n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('칼럼 방향으로 정렬: \n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]

### 2주차



*   저수준 API가 대부분인 넘파이의 데이터 핸들링은 편하다고 말하기 어려운데, 넘파이 기반으로 많은 부분이 작성된 판다스는 넘파이보다 훨씬 유연하고 편리하게 데이터 핸들링을 가능케 한다. 판다스는 파이썬의 리스트, 컬렉션, 넘파이 등의 내부 데이터뿐만 아니라 CSV 등의 파일을 쉽게 DataFrame으로 변경해 데이터의 가공 및 분석을 편리하게 수행할 수 있게 만들어준다.
*   판다스의 핵심 객체는 여러 개의 행과 열로 이뤄진 2차원 데이터를 담는 데이터 구조체인 DataFrame이다. Index는 RDBMS의 PK처럼 개별 데이터를 고유하게 식별하는 Key 값이다. Series와 DataFrame은 모두 Index를 Key 값으로 가지고 있는데, Series와 DataFrame의 가장 큰 차이는 Series는 칼럼이 하나 뿐인 데이터 구조체이고, DataFrame은 칼럼이 여러 개인 데이터 구조체라는 점이다. DataFrame은 여러 개의 Series로 이루어졌다고 할 수 있다. 판다스는 csv, tab과 같은 다양한 유형의 분리 문자로 칼럼을 분리한 파일을 손쉽게 DataFrame으로 로딩할 수 있게 해준다.
*   판다스는 다양한 포맷으로 된 파일을 DataFrame으로 로딩할 수 있는 편리한 API를 제공한다. 대표적으로 read_csv(), read_table(), read_fwf()가 있다. read_csv()는 이름에서도 알 수 있듯 CSV(칼럼을 ','로 구부한 파일 포맷) 파일 포맷 변환을 위한 API이다. read_table()과 read_csv()의 가장 큰 차이는 필드 구분 문자(Delimeter)가 콤마(')냐, 탭('\t')이냐의 차이이다. read_table()의 디폴트 필드 구분 문자는 탭 문자이다. read_csv()는 CSV뿐만 아니라 어떤 필드 구분 문자 기반의 파일 포맷도 DataFrame으로 변환이 가능한데, read_csv()의 인자인 sep에 해당 구분 문자를 입력하면 된다. 가령 탭으로 필드가 구분되어 있다면 read_csv('파일명', sep= '\t')처럼 쓰면 된다. read_csv()에서 sep 인자를 생략하면 자동으로 콤마로 할당한다. (sep = ','). read_csv()와 read_table()은 기능상 큰 차이가 없다. read_fwf()는 Fixed Width, 즉 고정 길이 기반의 칼럼 포맷을 DataFrame으로 로딩하기 위한 API이다.

In [12]:
import pandas as pd

In [14]:
titanic_df = pd.read_csv('/content/titanic_train.csv')
titanic_df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

*   DataFrame은 데이터뿐만 아니라 칼럼의 타입, Null 데이터 개수, 데이터 분포도 등의 메타 데이터 등도 조회가 가능하다. 이를 위한 대표적인 메서드로 info()와 describe()가 있다. info() 메서드를 통해서 총 데이터 건수, 데이터 타입, Null 건수를 알 수 있다. descirbe() 메서드는 칼럼별 숫자형 데이터값의 n-percentile 분포도, 평균값, 최댓값, 최솟값을 나타낸다. describe() 메서드는 오직 숫자형(int, float 등) 칼럼의 분포도만 조사하며 자동으로 object 타입의 칼럼은 출력에서 제외시킨다. describe() 메서드만으로 정확한 분포도를 알기는 무리지만, 대략적인 수준의 분포도를 확인할 수 있어 머신러닝 알고리즘 성능을 향상시키는 데 기여할 수 있다.
*  count는 Not Null인 데이터 건수, mean은 전체 데이터의 평균값, std는 표준편차이다. 사분위값들은 describe()는 해당 숫자 칼럼이 숫자형 카테고리 칼럼인지를 판단할 수 있게 도와준다. 카테고리 칼럼은 특정 범주에 속하는 값을 코드화한 칼럼이고, 이를 숫자로 표시할 수 있다.
*  DataFrame의 [] 연산자 내부에 칼럼명을 입력하면 Series 형태로 특정 칼럼 데이터 세트가 반환된다. 이렇게 반환된 Series 객체에 value_counts() 메서드를 호출하면 해당 칼럼값의 유형과 건수를 확인할 수 있다. value_counts()는 지정된 칼럼의 데이터값 건수를 반환한다. value_counts()는 데이터의 분포도를 확인하는 데 매우 유용한 함수이며, 많은 건수 순서대로 정렬해 값을 반환한다. DataFrame의 [] 연산자 내부에 칼럼명을 입력하면 해당 칼럼에 해당하는 Series 객체를 반환한다.

In [15]:
titanic_df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [16]:
value_counts = titanic_df['Pclass'].value_counts()
print(value_counts)

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [17]:
titanic_pclass = titanic_df['Pclass']
print(type(titanic_pclass))

<class 'pandas.core.series.Series'>

*  Series는 Index와 단 하나의 칼럼으로 구성된 데이터 세트이다. 한 개 칼럼의 데이터만 출력되지 않고 맨 왼쪽에 0부터 시작하는 순차 값이 있는데, 이것은 DataFrame의 인덱스와 동일한 인덱스이다. 오른쪽은 Series의 해당 칼럼의 데이터값이다. 모든 Series와 DataFrame은 인덱스를 반드시 가진다.
*  value_counts() 메서드는 단일 칼럼으로 되어 있는 Series 객체에서 호출하는 것이 칼럼별 데이터 값의 분포도를 더 명시적으로 파악하기 쉽다. DataFrame 객체에서도 물론 호출할 수 있다.
*  value_counts()가 반환하는 데이터 타입 역시 Series 객체이다. 반환된 Series 객체의 값을 보면 맨 왼쪽이 인덱스값이며, 오른쪽이 데이터값인데, 이번에는 인덱스가 단순히 0부터 시작하는 순차 값이 아니다. 이처럼 인덱스는 단순히 순차 값과 같은 의미 없는 식별자만 할당하는 것이 아니라 고유성이 보장된다면 의미 있는 데이터값 할당도 가능하다. value_counts()는 칼럼 값별 데이터 건수를 반환하므로 고유 칼럼 값을 식별자로 사용할 수 있다. 인덱스는 DataFrame, Series가 만들어진 이후에도 변경할 수 있으며, 숫자형뿐만 아니라 문자열도 가능하다. 단, 모든 인덱스는 고유성이 보장되어야 한다.
*  value_counts() 메서드를 사용할 때에는 Null 값을 무시하고 결과값을 내놓기 쉽다는 점을 유의해야 한다. value_counts()는 Null 값을 포함하여 개별 데이터 값의 건수를 계산할지를 dropna 인자로 판단한다. dropna의 기본값은 True이며, Null 값을 무시하고 개별 데이터 값의 건수를 계산한다. 만약 Null 값을 포함해 value_counts()를 적용하고자 한다면 value_counts(dropna = False)와 같이 dropna 인자값을 False로 입력해주면 된다.